name: Build App

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    tags-ignore:
      - '**'
    branches:
      - "**"
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '20 14 * * 1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET 10
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
