name: Build App

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    tags-ignore:
      - '**'
    branches:
      - "**"
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '20 14 * * 1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Setup .NET 7
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
