name: Release App

# When a release is published
on:
  release:
    types: [published]

jobs:
  release-windows:
    env:
      VERSION: ${{ github.event.release.tag_name }}
    runs-on: windows-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Setup .NET 7
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: 7.0.x
    - name: Copy Contributors
      run: |
        cp .all-contributorsrc AccountDownloader/Assets
    - name: Build Windows App
      run: |
        cd AccountDownloader
        dotnet publish -c Release -r win-x64 --self-contained -p:SourceRevisionId=${{github.run_id}} -p:Version=${{ env.VERSION }}
    - name: Archive Artifact
      run: |
        cd ResoniteAccountDownloader/bin/Release/net7.0/win-x64/publish
        powershell Compress-Archive -Path .\* -DestinationPath AccountDownloaderWindows.zip
    - name: Generate checksum
      uses:  ToxicAven/generate-checksum-file@66708d081e14d5616c5b0920ff9a127f6f499dee # v2
      with:
        filePath: ./ResoniteAccountDownloader/bin/Release/net7.0/win-x64/publish/AccountDownloaderWindows.zip
        saveFile: checksum-${{ env.VERSION }}-${{github.run_id}}-windows.txt
        algorithm: 'sha256'
    - name: Print Checksum
      run: type checksum-${{ env.VERSION }}-${{github.run_id}}-windows.txt
    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./ResoniteAccountDownloader/bin/Release/net7.0/win-x64/publish/AccountDownloaderWindows.zip
        asset_name: AccountDownloaderWindows-${{ env.VERSION }}.zip
    - name: Upload Checksum
      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: checksum-${{ env.VERSION }}-${{github.run_id}}-windows.txt
  release-linux:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Setup .NET 7
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: 7.0.x
    - name: Copy Contributors
      run: |
        cp .all-contributorsrc AccountDownloader/Assets
    - name: Build Linux app
      run: |
        cd AccountDownloader
        dotnet publish -c Release -r linux-x64 --self-contained=true -p:SourceRevisionId=${{github.run_id}} -p:Version=${{ env.VERSION }}
    - name: Archive Artifact
      run: |
        cd ResoniteAccountDownloader/bin/Release/net7.0/linux-x64/publish
        tar -czvf AccountDownloaderLinux.tar.gz ./*
    - name: Generate checksum
      uses:  ToxicAven/generate-checksum-file@66708d081e14d5616c5b0920ff9a127f6f499dee # v2
      with:
        filePath: ResoniteAccountDownloader/bin/Release/net7.0/linux-x64/publish/AccountDownloaderLinux.tar.gz
        saveFile: checksum-${{ env.VERSION }}-${{github.run_id}}-linux.txt
        algorithm: 'sha256'
    - name: Print Checksum
      run: cat checksum-${{ env.VERSION }}-${{github.run_id}}-linux.txt
    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ResoniteAccountDownloader/bin/Release/net7.0/linux-x64/publish/AccountDownloaderLinux.tar.gz
        asset_name: AccountDownloaderLinux-${{ env.VERSION }}.tar.gz
    - name: Upload Checksum
      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: checksum-${{ env.VERSION }}-${{github.run_id}}-linux.txt
